cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
  	path('', views.get, name='get'),
  	path('add/', views.add, name='add'),
  	path('update/', views.update, name='update'),
  	path('delete', views.delete, name='delete'),
]

djangoecom/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.core.validators import RegexValidator
from store.models import Order
from .cart import Cart

class PayForm(forms.ModelForm):
	phone_regex = RegexValidator(
		regex=r'^0\d{11}$',
		message="Phone number must start with 0 and contain 12 digits total. Format: 000000000000"
	)
	phone = forms.CharField(validators=[phone_regex], required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Phone Number'}))
	address = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Address'}))

	class Meta:
		model = Order
		fields = ('phone', 'address')

	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop('request', None)

		super(PayForm, self).__init__(*args, **kwargs)
		if self.request.user and hasattr(self.request.user, 'profile'):
			self.fields['phone'].initial = self.request.user.profile.phone

	def save(self, commit=True):
		instance = super().save(commit=False)
		instance.user = self.request.user
		cart = Cart(self.request)
		instance.total_price = cart.get_total_price()
		if commit:
			instance.save()
		return instance

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .cart import Cart
from store.models import Product
from django.http import JsonResponse
from django.contrib import messages
from .forms import PayForm
from store.models import OrderProduct
from django.db import transaction

def get(request):
	cart = Cart(request)
	cart_items = cart.get()

	if request.method == "POST":
		form = PayForm(data=request.POST, request=request)

		if not request.user.is_authenticated:
			messages.error(request, 'You have to be logged in to checkout')
			return render(request, "get.html", {'cart_items': cart_items, 'total': cart.get_total_price(), 'form': form}, status=401)
		
		if cart.__len__() == 0:
			messages.error(request, 'Empty cart')
			return render(request, "get.html", {'cart_items': cart_items, 'total': cart.get_total_price(), 'form': form}, status=422)
		
		if form.is_valid():
			with transaction.atomic():
				order = form.save()

				to_be_added = []
				for item in cart_items:
					to_be_added.append(
						OrderProduct(
							order=order,
							product_uuid=item['product'].uuid,
							name=item['product'].name,
							price=item['product'].price if not item['product'].is_sale else item['product'].sale_price,
							category_id=item['product'].category.id,
							category_name=item['product'].category.name,
							description=item['product'].description,
							image=item['product'].image,
							quantity=item['qty']
						)
					)
				OrderProduct.objects.bulk_create(to_be_added)
				cart.clear()
				return redirect('orders')
		return render(request, "get.html", {'cart_items': cart_items, 'total': cart.get_total_price(), 'form': form}, status=422)
	else:
		form = PayForm(request=request)
		
	return render(request, "get.html", {'cart_items': cart_items, 'total': cart.get_total_price(), 'form': form})

def add(request):
	cart = Cart(request)

	product_uuid = request.POST.get('product_uuid')
	qty = int(request.POST.get('qty'))
	if qty < 1:
		messages.error(request, 'quantity cannot be less than 1')
		return JsonResponse({'error': 'quantity cannot be less than 1'}, status=422)
	
	product = get_object_or_404(Product, uuid=product_uuid)

	cart.add(product=product, qty=qty)
	cart_qty = cart.__len__()

	messages.success(request, product.name + ' added to cart')

	return JsonResponse({'cart_qty': cart_qty})

def update(request):
	cart = Cart(request)

	product_uuid = request.POST.get('product_uuid')
	qty = int(request.POST.get('qty'))

	new_qty = cart.update(product_uuid=product_uuid, qty=qty)
	print(new_qty)

	return JsonResponse({'new_qty': new_qty})

def delete(request):
	cart = Cart(request)
	product_uuid = request.POST.get('product_uuid')
	cart.delete(product_uuid=product_uuid)

	return JsonResponse({'message': "delete successful"})

cart/templates/get.html
{% extends 'base.html' %}

{% block content %}

<div class="container mb-5 mt-3">
    {% if cart_items %}
    <div class="row">
        
        <div class="col-lg-8">
            <div class="card mb-4">
                <div class="card-body">
                    {% for item in cart_items %}
                    <div class="row mb-4" id="{{ item.product.uuid }}">
                        <div class="col-md-3">
                            <img src="{{ item.product.image.url }}" class="img-fluid rounded" alt="Product Image">
                        </div>
                        <div class="col-md-3">
                            <h5 class="card-title"><a href="{% url 'product' item.product.uuid %}">{{ item.product.name }}</a></h5>
                            <p class="text-muted small mb-2">
                                {% if item.product.description %}
                                {{ item.product.description|truncatechars:100 }}
                                {% endif %}
                            </p>
                            <button class="btn btn-link text-danger p-0 deleteitem" data-index="{{ item.product.uuid }}">
                                <i class="bi bi-trash"></i> Remove
                            </button>
                        </div>
                        <div class="col-md-2">
                            <div class="input-group input-group-sm">
                                <div method="POST" class="d-flex">
                                    <div class="input-group" style="width: 120px">
                                        <button class="btn btn-outline-secondary decrease" type="button" data-index="{{ item.product.uuid }}">-</button>
                                        <input type="number" class="form-control text-center px-0" value="{{ item.qty }}" 
                                            min="1" max="99" readonly id="qty{{ item.product.uuid }}">
                                        <button class="btn btn-outline-secondary increase" type="button" data-index="{{ item.product.uuid }}">+</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2 text-end">
                            {% if item.product.is_sale %}
                            <span class="h6">${{ item.product.sale_price }}</span>
                            <br>
                            <s class="small text-muted">${{ item.product.price }}</s>
                            {% else %}
                            <span class="h6">${{ item.product.price }}</span>
                            {% endif %}
                        </div>
                        <div class="col-md-2 text-end">
                            <span class="h6">Total: ${{ item.total }}</span>
                        </div>
                    </div>
                    {% if not forloop.last %}
                    <hr class="my-4">
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

        
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title mb-4">Order Summary</h5>
                    <div class="d-flex justify-content-between mb-4">
                        <strong>Total</strong>
                        <strong>${{ total|default:"0.00" }}</strong>
                    </div>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            {{ form.phone }}
                            {% if form.phone.errors %}
                                {% for error in form.phone.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="form-group mb-3">
                            {{ form.address }}
                            {% if form.address.errors %}
                                {% for error in form.address.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="d-grid gap-2">
                            <form>
                                <button class="btn btn-primary w-100">Proceed to Pay</button>
                            </form>
                            <a href="{% url 'home' %}" class="btn btn-outline-primary">Continue Shopping</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% else %}
    
    <div class="text-center py-5">
        <i class="bi bi-cart3 display-1 text-muted mb-4"></i>
        <h2>Your cart is empty</h2>
        <p class="text-muted mb-4">Looks like you haven't added any items to your cart yet.</p>
        <a href="{% url 'home' %}" class="btn btn-primary">Start Shopping</a>
    </div>
    {% endif %}
</div>

<script>
    $(document).on('click', '.increase', function(e) {
        e.preventDefault();
        let product_uuid = $(this).data('index');

        $.ajax({
            type: "POST",
            url: "{% url 'cart:update' %}",
            data: {
                product_uuid: product_uuid,
                qty: parseInt($('#qty' + product_uuid).val()) + 1,
                csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            success: function(json) {
                location.reload()
            },
            error: function(xhr, err_message, err) {

            }
        });
    });

    $(document).on('click', '.decrease', function(e) {
        e.preventDefault();
        let product_uuid = $(this).data('index');
        let currentQty = parseInt($('#qty' + product_uuid).val());
        
        if (currentQty > 1) {
            $.ajax({
                type: "POST",
                url: "{% url 'cart:update' %}",
                data: {
                    product_uuid: product_uuid,
                    qty: currentQty - 1,
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                success: function(json) {
                    location.reload()
                },
                error: function(xhr, err_message, err) {

                }
            });
        }
    });

    $(document).on('click', '.deleteitem', function(e) {
        e.preventDefault();
        let product_uuid = $(this).data('index');
        
        $.ajax({
            type: "POST",
            url: "{% url 'cart:delete' %}",
            data: {
                product_uuid: product_uuid,
                csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            success: function(json) {
                location.reload()
            },
            error: function(xhr, err_message, err) {

            }
        });
    });
</script>

{% endblock %}